FROM python:3.11-slim
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY ../../requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY ../../app /app/app
COPY . /app/services/worker
ENV PYTHONUNBUFFERED=1
CMD ["python", "services/worker/worker.py"]
